Repository fazer-ai/baileys-api, pull requests merged in 2025-07, with the labels that each got.

#62 chore: remove awaitResponse in handleMessagingHistorySet method
  src/baileys/connection.ts
Labels: enhancement, approved for merge

#73 feat: qrcode timeout
  .env.example
  README-pt.md
  README.md
  bun.lock
  package.json
  src/baileys/connection.ts
  src/config.ts
Labels: enhancement

#79 fix: catch logout errors
  src/baileys/connection.ts
Labels: bug

#81 feat: ignore non-user messages by default
  .env.example
  README-pt.md
  README.md
  src/baileys/connection.ts
  src/baileys/helpers/shouldIgnoreJid.ts
  src/config.ts
Labels: enhancement
